name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build and deploy
      run: |
        # Replace with your build and deploy commands
        npm run build
        npm run deploy
      env:
        # Define your environment variables here
        GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
        GOOGLE_SECRET:  ${{ secrets.GOOGLE_SECRET }}
        AUTH_SECRET:  ${{ secrets.AUTH_SECRET }}
        NEXTAUTH_URL:  ${{ secrets.NEXTAUTH_URL }}
        MONGODB_URI:  ${{ secrets.MONGODB_URI }}
        SPACES_ACCESS_KEY:  ${{ secrets.SPACES_ACCESS_KEY }}
        SPACES_SECRET_KEY:  ${{ secrets.SPACES_SECRET_KEY }}
        DO_SPACES_BUCKET:  ${{ secrets.DO_SPACES_BUCKET }}
        NEXT_PUBLIC_NEXTAUTH_URL: ${{secret.NEXT_PUBLIC_NEXTAUTH_URL}}
        NEXT_PUBLIC_API_URL: ${{secret.NEXT_PUBLIC_API_URL}}        
        NEXTAUTH_URL_DASHBOARD: ${{secret.NEXTAUTH_URL_DASHBOARD}}
        NEXT_PUBLIC_DOSPACES_BUCKET: ${{secret.NEXT_PUBLIC_DOSPACES_BUCKET}}