name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          yarn-version: 1.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SPACES_ACCESS_KEY: ${{ secrets.SPACES_ACCESS_KEY }}
          SPACES_SECRET_KEY: ${{ secrets.SPACES_SECRET_KEY }}
          DO_SPACES_BUCKET: ${{ secrets.DO_SPACES_BUCKET }}
          NEXT_PUBLIC_NEXTAUTH_URL: ${{ secrets.NEXT_PUBLIC_NEXTAUTH_URL }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXTAUTH_URL_DASHBOARD: ${{ secrets.NEXTAUTH_URL_DASHBOARD }}
          NEXT_PUBLIC_DOSPACES_BUCKET: ${{ secrets.NEXT_PUBLIC_DOSPACES_BUCKET }}

      - name: Transfer files to DigitalOcean Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          source: "."
          target: "/var/www/nextjs"
          port: 22

      - name: Install dependencies and Restart application on DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
          script: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            nvm install 16
            nvm use 16
            cd /var/www/nextjs
            export GOOGLE_ID=${{ secrets.GOOGLE_ID }}
            export GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}
            export AUTH_SECRET=${{ secrets.AUTH_SECRET }}
            export NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            export MONGODB_URI=${{ secrets.MONGODB_URI }}
            export SPACES_ACCESS_KEY=${{ secrets.SPACES_ACCESS_KEY }}
            export SPACES_SECRET_KEY=${{ secrets.SPACES_SECRET_KEY }}
            export DO_SPACES_BUCKET=${{ secrets.DO_SPACES_BUCKET }}
            export NEXT_PUBLIC_NEXTAUTH_URL=${{ secrets.NEXT_PUBLIC_NEXTAUTH_URL }}
            export NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            export NEXTAUTH_URL_DASHBOARD=${{ secrets.NEXTAUTH_URL_DASHBOARD }}
            export NEXT_PUBLIC_DOSPACES_BUCKET=${{ secrets.NEXT_PUBLIC_DOSPACES_BUCKET }}
            yarn install --frozen-lockfile
            yarn build
            yarn global add pm2
            pm2 restart all